FROM python:3.11

# Set working directory
WORKDIR /usr/src/app

# Copy ML code
COPY ML/ .

# Install Python dependencies
RUN pip install --no-cache-dir fastapi uvicorn pandas joblib prophet

# Expose FastAPI port
EXPOSE 8001

# Start FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
