version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-farmers2marketapp
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./Farmers2MarketApp:/var/www/html
    depends_on:
      - db
      - ml
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "AgriConnect"
      APP_ENV: "local"
      APP_DEBUG: "true"
      APP_KEY: "base64:PAzSLvMkz5p4ev2UqxYCGFjmmE0STUv1EX8WseeWZQY="
      APP_URL: "http://localhost:8000"
      DB_CONNECTION: "mysql"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Agriconnectnew
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    command: sh -c "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: agriconnectnew
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Agriconnectnew.sql:/docker-entrypoint-initdb.d/Agriconnectnew.sql

  ml:
    build:
      context: .
      dockerfile: Dockerfile-ml
    container_name: ml_service
    ports:
      - "8001:8001"

volumes:
  db_data:
