version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "AgriConnect"
      APP_ENV: "production"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "false"
      APP_URL: "http://localhost:8000"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "railway"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      MAIL_MAILER: "smtp"
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: 587
      MAIL_USERNAME: "youremail@gmail.com"
      MAIL_PASSWORD: "your-app-password"
      MAIL_ENCRYPTION: "tls"
      MAIL_FROM_ADDRESS: "youremail@gmail.com"
      MAIL_FROM_NAME: "AgriConnect"
      PAYHERE_MERCHANT_ID: "123456"
      PAYHERE_MERCHANT_SECRET: "secret"
      PAYHERE_SANDBOX: "true"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "railway"
    ports:
      - "3306:3306"
