version: '3.8'

services:
  app:
    build:
      context: .        # <-- THIS MUST BE A STRING, '.' means current folder
      dockerfile: Dockerfile
    image: agri-connect-app
    container_name: agri-connect-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:gn0sQB3tIxr2Rvpa6psfg+2uiGaQXeUCespvxBLQMVc=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=Agriconnectnew
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: agri-connect-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Agriconnectnew
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
