[phases.setup]
nixPkgs = [
    'php82',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.mbstring',
    'php82Extensions.xml',
    'php82Extensions.zip',
    'php82Extensions.gd',
    'php82Extensions.curl',
    'php82Extensions.fileinfo',
    'php82Extensions.tokenizer',
    'php82Extensions.bcmath',
    'php82Extensions.ctype',
    'php82Extensions.json',
    'php82Extensions.openssl',
    'php82Extensions.pcntl',
    'php82Extensions.posix'
]

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
    'mkdir -p storage/framework/{sessions,views,cache}',
    'mkdir -p storage/logs',
    'chmod -R 775 storage bootstrap/cache',
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=$PORT --workers=4 --max-requests=500'