[build]
# Optional: Composer install if not in Dockerfile
build = "composer install --no-dev --optimize-autoloader"

[deploy]
# Pre-deploy commands
predeploy = """
if [ -f artisan ]; then
    php artisan key:generate --force || echo 'Key exists'
    php artisan config:clear
    php artisan cache:clear
    php artisan route:clear
    php artisan view:clear
fi
"""

# Start command
start = "php artisan serve --host=0.0.0.0 --port=$PORT"
