# Railway Laravel build configuration (for Railpack)

[build]
# PHP Extensions you want to include
php_extensions = [
  "pdo",
  "pdo_mysql",
  "mysqli",
  "mbstring",
  "openssl",
  "tokenizer",
  "xml",
  "curl",
  "ctype",
  "bcmath",
  "fileinfo"
]

# Set PHP and Node versions explicitly
php_version = "8.2"
node_version = "22"

# Pre-deploy command (optional)
# This runs before starting your container
pre_deploy = "php artisan migrate --force"
