# Railpack build configuration for Laravel

[build]
php_version = "8.2"
node_version = "22"

php_extensions = [
  "pdo_mysql",
  "mysqli",
  "mbstring",
  "openssl",
  "tokenizer",
  "xml",
  "curl",
  "ctype",
  "bcmath",
  "fileinfo"
]

# Optional pre-deploy hook to run migrations
# (disable temporarily if it causes errors)
pre_deploy = "php artisan migrate --force"
[project]
name = "AgriConnect"
environment = "production"

[service]
name = "app"
build = "docker build -t agriconnect ."
start = "php artisan serve --host=0.0.0.0 --port=$PORT"
port = 8080

[env]
APP_NAME = "AgriConnect"
APP_ENV = "production"
APP_KEY = "${APP_KEY}"
APP_DEBUG = "false"
APP_URL = "https://<your-railway-domain>.up.railway.app"

DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"
