# Railpack build configuration for Laravel

[build]
php_version = "8.2"
node_version = "22"

php_extensions = [
  "pdo_mysql",
  "mysqli",
  "mbstring",
  "openssl",
  "tokenizer",
  "xml",
  "curl",
  "ctype",
  "bcmath",
  "fileinfo"
]

# Optional pre-deploy hook to run migrations
# (disable temporarily if it causes errors)
pre_deploy = "php artisan migrate --force"
